# Generated by Django 4.1.5 on 2023-01-30 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_key', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('embedding_model', models.CharField(default='text-embedding-ada-002', max_length=100)),
                ('embedding_dim', models.IntegerField(default=1056)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('url', models.CharField(blank=True, max_length=300)),
                ('page', models.IntegerField(default=0)),
                ('internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('indexed', models.BooleanField(default=False)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.realm')),
            ],
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_key', models.CharField(max_length=200)),
                ('prompt_template', models.TextField()),
                ('model', models.CharField(default='text-davinci-003', max_length=200)),
                ('model_max_tokens', models.IntegerField(default=4096)),
                ('max_tokens', models.IntegerField(default=720)),
                ('temperature', models.FloatField(default=0.9)),
                ('presence_penality', models.FloatField(default=0)),
                ('frequency_penality', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('public', models.BooleanField(default=False)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.realm')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
