# Generated by Django 4.1.5 on 2023-01-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_realm_embedding_dim_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
