# Generated by Django 4.1.5 on 2023-01-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_question_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
