# Generated by Django 4.1.5 on 2023-02-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_text_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Text'},
        ),
        migrations.AddField(
            model_name='chatbot',
            name='openai_org',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='realm',
            name='openai_org',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
