# Generated by Django 4.1.7 on 2023-02-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_question_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
