# Generated by Django 4.1.7 on 2023-03-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_question_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='restricted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=200),
        ),
    ]
