# Generated by Django 4.1.7 on 2023-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_chatbot_restricted_alter_chatbot_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='skip_context',
            field=models.BooleanField(default=False),
        ),
    ]
